/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResolutionsRouteImport } from './routes/resolutions'
import { Route as MinutesRouteImport } from './routes/minutes'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as DirectorsRouteImport } from './routes/directors'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolutionsRoute = ResolutionsRouteImport.update({
  id: '/resolutions',
  path: '/resolutions',
  getParentRoute: () => rootRouteImport,
} as any)
const MinutesRoute = MinutesRouteImport.update({
  id: '/minutes',
  path: '/minutes',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorsRoute = DirectorsRouteImport.update({
  id: '/directors',
  path: '/directors',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/directors': typeof DirectorsRoute
  '/entities': typeof EntitiesRoute
  '/minutes': typeof MinutesRoute
  '/resolutions': typeof ResolutionsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/directors': typeof DirectorsRoute
  '/entities': typeof EntitiesRoute
  '/minutes': typeof MinutesRoute
  '/resolutions': typeof ResolutionsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/directors': typeof DirectorsRoute
  '/entities': typeof EntitiesRoute
  '/minutes': typeof MinutesRoute
  '/resolutions': typeof ResolutionsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/directors'
    | '/entities'
    | '/minutes'
    | '/resolutions'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/directors'
    | '/entities'
    | '/minutes'
    | '/resolutions'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/directors'
    | '/entities'
    | '/minutes'
    | '/resolutions'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DirectorsRoute: typeof DirectorsRoute
  EntitiesRoute: typeof EntitiesRoute
  MinutesRoute: typeof MinutesRoute
  ResolutionsRoute: typeof ResolutionsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolutions': {
      id: '/resolutions'
      path: '/resolutions'
      fullPath: '/resolutions'
      preLoaderRoute: typeof ResolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minutes': {
      id: '/minutes'
      path: '/minutes'
      fullPath: '/minutes'
      preLoaderRoute: typeof MinutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directors': {
      id: '/directors'
      path: '/directors'
      fullPath: '/directors'
      preLoaderRoute: typeof DirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DirectorsRoute: DirectorsRoute,
  EntitiesRoute: EntitiesRoute,
  MinutesRoute: MinutesRoute,
  ResolutionsRoute: ResolutionsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
